/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kenken.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.InputStream;
import java.time.Duration;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import kenken.domain.classes.Pos;
import kenken.domain.classes.Region;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author SuNLoCK
 */
public class CreatePanel extends javax.swing.JPanel {
    private MainWindow mw;
    private boolean editing = false;
    private int countregions = 1;
    private int size;
    
    //Deberías poner aquí un Duration que cada segundo1 del Timer cambie, y que
    //cuando se produzca el evento suba un segundo al Duration, y que sea éste
    //el que aparezca en pantalla en el lblTime
    /**
     * Creates new form PlayPanel
     */
    public CreatePanel(MainWindow mw) {
        initComponents();
        this.mw = mw;
        spnRegion.setModel(new javax.swing.SpinnerNumberModel(1, 1, countregions, 1));
        cmbOperation.setModel(new javax.swing.DefaultComboBoxModel(Region.OperationType.values()));
        editorPanel1.setCreatorController(mw.getCreatorController());
    }
    
    /**
     * Initializes a Board.
     * @param size Indicates the size of the Board.
     */
    public void initBoard(int size) {
        this.size = size;
        countregions = 1;
        editing = false;
        spnRegion.setModel(new javax.swing.SpinnerNumberModel(1, 1, countregions, 1));
        cmbOperation.setModel(new javax.swing.DefaultComboBoxModel(Region.OperationType.values()));
        txtResult.setText("1");
        btnSaveBoard.setEnabled(false);
        
        ArrayList<ArrayList<InfoCell>> infoCells = new ArrayList<>(size);
        
        for (int i = 0; i < size; ++i) 
        {
            infoCells.add(new ArrayList<>(size));
            for (int j = 0; j < size; ++j) 
            {
                infoCells.get(i).add(new InfoCell());
            }
        }
        
        editorPanel1.setInfoCells(infoCells);
        editorPanel1.setShowRegionNumber(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClear = new javax.swing.JButton();
        btnCheckBoard = new javax.swing.JButton();
        lblShowStatus = new javax.swing.JLabel();
        editorPanel1 = new kenken.gui.EditorPanel();
        btnSaveBoard = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        lblRegion = new javax.swing.JLabel();
        btnMakeRegion = new javax.swing.JButton();
        lblOperation = new javax.swing.JLabel();
        cmbOperation = new javax.swing.JComboBox();
        spnRegion = new javax.swing.JSpinner();
        btnExit = new javax.swing.JButton();

        btnClear.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setToolTipText("");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCheckBoard.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        btnCheckBoard.setText("FIND SOLUTION");
        btnCheckBoard.setToolTipText("");
        btnCheckBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBoardActionPerformed(evt);
            }
        });

        lblShowStatus.setFont(new java.awt.Font("Flubber", 0, 14)); // NOI18N

        javax.swing.GroupLayout editorPanel1Layout = new javax.swing.GroupLayout(editorPanel1);
        editorPanel1.setLayout(editorPanel1Layout);
        editorPanel1Layout.setHorizontalGroup(
            editorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        editorPanel1Layout.setVerticalGroup(
            editorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        btnSaveBoard.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        btnSaveBoard.setText("SAVE BOARD");
        btnSaveBoard.setToolTipText("");
        btnSaveBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBoardActionPerformed(evt);
            }
        });

        btnExit1.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        btnExit1.setText("HELP");
        btnExit1.setToolTipText("");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit"));

        lblResult.setFont(new java.awt.Font("Flubber", 0, 14)); // NOI18N
        lblResult.setText("Result:");

        txtResult.setFont(new java.awt.Font("Flubber", 0, 14)); // NOI18N
        txtResult.setText("1");

        lblRegion.setFont(new java.awt.Font("Flubber", 0, 14)); // NOI18N
        lblRegion.setText("Region:");

        btnMakeRegion.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        btnMakeRegion.setText("Make Region");
        btnMakeRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeRegionActionPerformed(evt);
            }
        });

        lblOperation.setFont(new java.awt.Font("Flubber", 0, 14)); // NOI18N
        lblOperation.setText("Operation:");

        cmbOperation.setFont(new java.awt.Font("Flubber", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegion)
                .addGap(18, 18, 18)
                .addComponent(spnRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblOperation)
                .addGap(18, 18, 18)
                .addComponent(cmbOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResult)
                .addGap(18, 18, 18)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMakeRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(spnRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblRegion)
                .addComponent(lblOperation)
                .addComponent(cmbOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblResult)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMakeRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnExit.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.setToolTipText("");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnCheckBoard)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblShowStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnSaveBoard)
                                .addGap(20, 20, 20)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(editorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(lblShowStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCheckBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Shows up a Confirmation Dialog and switches to Main Menu Panel.
     * @param evt Event trigger.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "Are you sure you want to quit? All changes in board will be not saved.", "Warning", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            mw.setPanel(MainWindow.Panels.MainMenuPanel);
        }
    }//GEN-LAST:event_btnExitActionPerformed
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        mw.getCreatorController().initNewBoard(size);      
        initBoard(size);
        repaint();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * Checks if the Board have a solution.
     * @param evt Event trigger.
     */
    private void btnCheckBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckBoardActionPerformed
        Object[] options = {"OK"};
        boolean correct = mw.getCreatorController().resolve(editorPanel1.getInfoCells());
        if (correct){
            JOptionPane.showOptionDialog(this,"This Board have a correct solution!.","Correct",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            btnSaveBoard.setEnabled(true);
            
            ArrayList<ArrayList<Integer>> values = mw.getCreatorController().getSolutionValues();
            ArrayList<ArrayList<InfoCell>> infoCells = editorPanel1.getInfoCells();
            
            for (int f = 0; f < values.size(); ++f) {
                for (int c = 0; c < values.size(); ++c) {
                    infoCells.get(f).get(c).value = String.valueOf(values.get(f).get(c));
                }
            }  
            repaint();
        }else{
            JOptionPane.showOptionDialog(this,"This Board DO NOT have a correct solution.","Inorrect",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        }
    }//GEN-LAST:event_btnCheckBoardActionPerformed

    /**
     * Let us to a create a shape for a region.
     * @param evt Event trigger.
     */
    private void btnMakeRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeRegionActionPerformed
        
        if(! editing) {
            
            editorPanel1.setEditRegionMode(true);
            Integer regionNumber = (Integer) spnRegion.getValue();
            String operation = convertToSimbol((Region.OperationType)cmbOperation.getSelectedItem());
            String result = txtResult.getText();
            
            editorPanel1.setEditRegionNumber(regionNumber);
            editorPanel1.setEditRegionOperation(operation);
            editorPanel1.setEditRegionResult(result);
            btnMakeRegion.setText("End Region");
            
            spnRegion.setEnabled(false);
            cmbOperation.setEnabled(false);
            editing = true;
            
            
            if (!mw.getCreatorController().existRegion(regionNumber)) {
               Region.OperationType op =  convertToOperation(operation);
                              
               mw.getCreatorController().addRegion(regionNumber, op, Integer.parseInt(result), true);
            }
        }
        else {
            editorPanel1.setEditRegionMode(false);
            btnMakeRegion.setText("Make Region");
            
            spnRegion.setModel(new javax.swing.SpinnerNumberModel(1, 1, ++countregions, 1));
            spnRegion.setValue(countregions);
            
            spnRegion.setEnabled(true);
            cmbOperation.setEnabled(true);
            editing = false;
        }
        
    }//GEN-LAST:event_btnMakeRegionActionPerformed

    /**
     * Saves the Board if haves a solution.
     * @param evt 
     */
    private void btnSaveBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBoardActionPerformed
        Object[] options = {"OK"};
        int result = -1;
        String message = "Insert Board name:";
        while (result == -1){
            String boardname =  JOptionPane.showInputDialog(this, message, "Save",
                    JOptionPane.QUESTION_MESSAGE);    
            if (boardname != "") {
                result = mw.getCreatorController().saveBoard(boardname,mw.getUserController().getUsername());
                message = "Boardname in use. Please insert another Board name:";
            }else{
                message = "Please insert a Board name:";
            }     
        }
        if (result == 0){  
            JOptionPane.showOptionDialog(this,"Board saved.","Success",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        }else{
            JOptionPane.showOptionDialog(this,"Internal Error.","Error",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        }
    }//GEN-LAST:event_btnSaveBoardActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private String convertToSimbol(Region.OperationType op) {
        switch(op) {
            case Add:
                return "+";
            case Subtract:
                return "-";
            case Multiply:
                return "*";
            case Divide:
                return "/";
            case None:
                return "";
            default:
                throw new AssertionError(op.name());

        }
    }
    
    /**
     * Converts a symbol of a region to a OperationType.
     * @param symbol Symbol wanted to convert.
     * @return An OperationType related to its symbol.
     */
    public Region.OperationType convertToOperation(String symbol){ 

        switch(symbol) {
            case "+":
                return Region.OperationType.Add;
            case "-":
                return Region.OperationType.Subtract;
            case "*":
                return Region.OperationType.Multiply;
            case "/":
                return Region.OperationType.Divide;
            case "":
                return Region.OperationType.None;
            default:
                throw new AssertionError("Simbolo desconocido.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckBoard;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnMakeRegion;
    private javax.swing.JButton btnSaveBoard;
    private javax.swing.JComboBox cmbOperation;
    private kenken.gui.EditorPanel editorPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblOperation;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblShowStatus;
    private javax.swing.JSpinner spnRegion;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
