/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kenken.gui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import kenken.domain.controllers.RankingController;

/**
 *
 * @author asus
 */
public class EndGamePanel extends javax.swing.JPanel {
    
    private DefaultTableModel tableModel;
    private MainWindow mw;
    private String boardPlayed;
    private RankingController rc;
    private DefaultTableModel dtm;
    /**
     * Creates new form EndGamePanel
     * @param mw
     */
    public EndGamePanel(MainWindow mw) {
        initComponents();
        this.mw = mw;
        this.rc = this.mw.getRankingController();
        this.dtm = (DefaultTableModel) tblRanking.getModel();
    }
    
    public void clearRecordsList(){
        int size = tblRanking.getRowCount();
        for (int i = 0; i < size; i++){
            this.dtm.removeRow(0);
        }
    }
    
    /**
     * Sets the Ranking List every time we enter the End Game Panel.
     */
    public void updateList(){
        /*tableModel = (DefaultTableModel) tblRanking.getModel();
        
        ArrayList<String> records = mw.getRankingController().getStringRanking(boardPlayed);
        for(int i=0;i<records.size();i+=2){
            tableModel.addRow(new Object[]{records.get(i+1),records.get(i)});
        }*/
        
        ArrayList<String> show = rc.showRanking(boardPlayed);
        show.remove(show.size() - 1);
        show.remove(0);
        for(int i = 0; i < show.size(); i += 2){
            String[] row = {show.get(i), show.get(i + 1)};
            this.dtm.addRow(row);
        }
    }
    
    /**
     * Sets the info boardPlayed.
     * @param boardPlayed The boardPlayed in the game.
     */
    public void setBoardPlayed(String boardPlayed){
        this.boardPlayed = boardPlayed;
        lblBoardName.setText(boardPlayed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBoardName = new javax.swing.JLabel();
        lblCongrats = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRanking = new javax.swing.JTable();
        lblRankStats = new javax.swing.JLabel();

        lblBoardName.setFont(new java.awt.Font("Flubber", 0, 24)); // NOI18N

        lblCongrats.setFont(new java.awt.Font("Flubber", 0, 36)); // NOI18N
        lblCongrats.setText("Congratulations ! You have succeed !");

        btnBack.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        btnBack.setText("Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblRanking.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        tblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "SCORE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRanking);
        if (tblRanking.getColumnModel().getColumnCount() > 0) {
            tblRanking.getColumnModel().getColumn(0).setResizable(false);
            tblRanking.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblRanking.getColumnModel().getColumn(1).setResizable(false);
            tblRanking.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        lblRankStats.setFont(new java.awt.Font("Flubber", 0, 24)); // NOI18N
        lblRankStats.setText("Rank stats for Board");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCongrats, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lblRankStats, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBoardName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblCongrats, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRankStats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Switches to Main Menu Panel when Back button is pressed.
     * @param evt Event trigger.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mw.setPanel(MainWindow.Panels.MainMenuPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBoardName;
    private javax.swing.JLabel lblCongrats;
    private javax.swing.JLabel lblRankStats;
    private javax.swing.JTable tblRanking;
    // End of variables declaration//GEN-END:variables
}
