/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kenken.gui;

/**
 *
 * @author Marc
 */
public class GenerateBoardPanel extends javax.swing.JPanel {

    private MainWindow mw;
    /**
     * Creates new form GenerateBoardPanel
     */
    public GenerateBoardPanel(MainWindow mw) {
        initComponents();
        this.mw = mw;
        txtSeed.setText(String.valueOf(System.nanoTime()));
    }
    
    private static float selectDifficult(String diff){
        float res;
        if ("Easy".equals(diff)) res = 0.7f;
        else if ("Medium".equals(diff)) res = 1.2f;
        else if ("Hard".equals(diff)) res = 1.7f;
        else res = 2;
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGameMode = new javax.swing.JLabel();
        cmbbGameMode = new javax.swing.JComboBox();
        lblSize = new javax.swing.JLabel();
        cmbbSize = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        lblGenerateBoard = new javax.swing.JLabel();
        lblDifficult = new javax.swing.JLabel();
        cmbDifficult = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sldRegionFactor = new javax.swing.JSlider();
        txtRegionFactor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sldOperationFactor = new javax.swing.JSlider();
        txtOperationFactor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSeed = new javax.swing.JTextField();
        btnPlay = new javax.swing.JButton();

        lblGameMode.setFont(new java.awt.Font("Flubber", 0, 24)); // NOI18N
        lblGameMode.setText("Game Mode:");

        cmbbGameMode.setFont(new java.awt.Font("Flubber", 0, 24)); // NOI18N
        cmbbGameMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "TimeAttack" }));

        lblSize.setFont(new java.awt.Font("Flubber", 0, 24)); // NOI18N
        lblSize.setText("Size:");

        cmbbSize.setFont(new java.awt.Font("Flubber", 0, 24)); // NOI18N
        cmbbSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5", "6", "7", "8", "9" }));

        btnBack.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblGenerateBoard.setFont(new java.awt.Font("Flubber", 0, 48)); // NOI18N
        lblGenerateBoard.setText("GENERATE BOARD");

        lblDifficult.setFont(new java.awt.Font("Flubber", 0, 24)); // NOI18N
        lblDifficult.setText("Difficulty:");

        cmbDifficult.setFont(new java.awt.Font("Flubber", 0, 24)); // NOI18N
        cmbDifficult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Easy", "Medium", "Hard", "Insane" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Advanced"));

        jLabel1.setText("Difficult Region Size");

        sldRegionFactor.setMaximum(200);
        sldRegionFactor.setMinimum(1);
        sldRegionFactor.setValue(100);
        sldRegionFactor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldRegionFactorStateChanged(evt);
            }
        });

        txtRegionFactor.setText("1.0");
        txtRegionFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegionFactorActionPerformed(evt);
            }
        });

        jLabel2.setText("Difficult Operation");

        sldOperationFactor.setMaximum(200);
        sldOperationFactor.setMinimum(1);
        sldOperationFactor.setValue(100);
        sldOperationFactor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldOperationFactorStateChanged(evt);
            }
        });

        txtOperationFactor.setText("1.0");

        jLabel3.setText("Seed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sldRegionFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegionFactor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sldOperationFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOperationFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSeed, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRegionFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtSeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sldRegionFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(sldOperationFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtOperationFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        btnPlay.setFont(new java.awt.Font("Flubber", 0, 36)); // NOI18N
        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 125, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(lblGenerateBoard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDifficult, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbbGameMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbbSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDifficult, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblGenerateBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbbGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDifficult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDifficult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mw.setPanel(MainWindow.Panels.NewGamePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        String mode = (String) cmbbGameMode.getSelectedItem();
        int size = Integer.parseInt((String) cmbbSize.getSelectedItem());
        float pfRegionSize = Float.parseFloat(txtRegionFactor.getText());
        float pfOperation = Float.parseFloat(txtOperationFactor.getText());
        long seed = Long.parseLong(txtSeed.getText());
        
        
        
        mw.getGameController().newGameGenerateBoard(mode, size, pfRegionSize, 
                pfOperation, seed);
        
        PlayPanel pp = (PlayPanel) mw.getPanel(MainWindow.Panels.PlayPanel);
        pp.clearPanel();
        pp.initBoard(mw.getGameController().getInfoBoard());
        pp.setNotLoaded();
        mw.setPanel(MainWindow.Panels.PlayPanel);
        ((PlayPanel) mw.getPanel(MainWindow.Panels.PlayPanel)).initTime();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void txtRegionFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegionFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegionFactorActionPerformed

    private void sldRegionFactorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldRegionFactorStateChanged
        double value = sldRegionFactor.getValue();
        
        txtRegionFactor.setText(String.valueOf(value/100.0));
    }//GEN-LAST:event_sldRegionFactorStateChanged

    private void sldOperationFactorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldOperationFactorStateChanged
        double value = sldOperationFactor.getValue();
        
        txtOperationFactor.setText(String.valueOf(value/100.0));
    }//GEN-LAST:event_sldOperationFactorStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPlay;
    private javax.swing.JComboBox cmbDifficult;
    private javax.swing.JComboBox cmbbGameMode;
    private javax.swing.JComboBox cmbbSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDifficult;
    private javax.swing.JLabel lblGameMode;
    private javax.swing.JLabel lblGenerateBoard;
    private javax.swing.JLabel lblSize;
    private javax.swing.JSlider sldOperationFactor;
    private javax.swing.JSlider sldRegionFactor;
    private javax.swing.JTextField txtOperationFactor;
    private javax.swing.JTextField txtRegionFactor;
    private javax.swing.JTextField txtSeed;
    // End of variables declaration//GEN-END:variables
}
