/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kenken.gui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import kenken.domain.controllers.RankingController;

/**
 *
 * @author Marc
 */
public class RankingPanel extends javax.swing.JPanel {

    private MainWindow mw;
    private RankingController rc;
    private DefaultTableModel dtm;
    
    /**
     * Creates new form RankingPanel
     * @param mw Main Window Controller.
     */
    public RankingPanel(MainWindow mw) {
        initComponents();
        this.mw = mw;
        this.rc = this.mw.getRankingController();
        this.dtm = (DefaultTableModel) tblRanking.getModel();
    }
    
    /**
     * Sets the list of record in the ranking.
     * @param boardname The boardname related to the ranking.
     */
    public void setRecordsList(String boardname){
        ArrayList<String> show = rc.showRanking(boardname);
        show.remove(show.size() - 1);
        show.remove(0);
        for(int i = 0; i < show.size(); i += 2){
            String[] row = {show.get(i), show.get(i + 1)};
            this.dtm.addRow(row);
        }
    }
    
    /**
     * Clears the List of records.
     */
    public void clearRecordsList(){
        int size = tblRanking.getRowCount();
        for (int i = 0; i < size; i++){
            this.dtm.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRanking = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        scrllRanking = new javax.swing.JScrollPane();
        tblRanking = new javax.swing.JTable();

        lblRanking.setFont(new java.awt.Font("Flubber", 0, 48)); // NOI18N
        lblRanking.setText("BEST SCORES ALL TIME");
        lblRanking.setToolTipText("");

        btnBack.setFont(new java.awt.Font("Flubber", 0, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblRanking.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player", "Record"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRanking.setRowHeight(30);
        tblRanking.setShowHorizontalLines(false);
        tblRanking.setShowVerticalLines(false);
        tblRanking.getTableHeader().setReorderingAllowed(false);
        scrllRanking.setViewportView(tblRanking);
        if (tblRanking.getColumnModel().getColumnCount() > 0) {
            tblRanking.getColumnModel().getColumn(0).setResizable(false);
            tblRanking.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(scrllRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lblRanking)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(scrllRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Switches to Choose Ranking Panel when Back button is pressed.
     * @param evt Event trigger.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mw.setPanel(MainWindow.Panels.ChooseRankingPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JScrollPane scrllRanking;
    private javax.swing.JTable tblRanking;
    // End of variables declaration//GEN-END:variables
}
